//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace testWCFService.INetLibService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookEntity", Namespace="http://schemas.datacontract.org/2004/07/BookEntity")]
    [System.SerializableAttribute()]
    public partial class BookEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private testWCFService.INetLibService.Authors authorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int bookIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bookRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dateAddedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string extensionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int fileSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private testWCFService.INetLibService.Genres genresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isDeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string keywordsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string languageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int numberInSeriesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string seriesTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string titleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public testWCFService.INetLibService.Authors authors {
            get {
                return this.authorsField;
            }
            set {
                if ((object.ReferenceEquals(this.authorsField, value) != true)) {
                    this.authorsField = value;
                    this.RaisePropertyChanged("authors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int bookID {
            get {
                return this.bookIDField;
            }
            set {
                if ((this.bookIDField.Equals(value) != true)) {
                    this.bookIDField = value;
                    this.RaisePropertyChanged("bookID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bookRate {
            get {
                return this.bookRateField;
            }
            set {
                if ((object.ReferenceEquals(this.bookRateField, value) != true)) {
                    this.bookRateField = value;
                    this.RaisePropertyChanged("bookRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dateAdded {
            get {
                return this.dateAddedField;
            }
            set {
                if ((object.ReferenceEquals(this.dateAddedField, value) != true)) {
                    this.dateAddedField = value;
                    this.RaisePropertyChanged("dateAdded");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string extension {
            get {
                return this.extensionField;
            }
            set {
                if ((object.ReferenceEquals(this.extensionField, value) != true)) {
                    this.extensionField = value;
                    this.RaisePropertyChanged("extension");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.fileNameField, value) != true)) {
                    this.fileNameField = value;
                    this.RaisePropertyChanged("fileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int fileSize {
            get {
                return this.fileSizeField;
            }
            set {
                if ((this.fileSizeField.Equals(value) != true)) {
                    this.fileSizeField = value;
                    this.RaisePropertyChanged("fileSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public testWCFService.INetLibService.Genres genres {
            get {
                return this.genresField;
            }
            set {
                if ((object.ReferenceEquals(this.genresField, value) != true)) {
                    this.genresField = value;
                    this.RaisePropertyChanged("genres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isDeleted {
            get {
                return this.isDeletedField;
            }
            set {
                if ((this.isDeletedField.Equals(value) != true)) {
                    this.isDeletedField = value;
                    this.RaisePropertyChanged("isDeleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string keywords {
            get {
                return this.keywordsField;
            }
            set {
                if ((object.ReferenceEquals(this.keywordsField, value) != true)) {
                    this.keywordsField = value;
                    this.RaisePropertyChanged("keywords");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string language {
            get {
                return this.languageField;
            }
            set {
                if ((object.ReferenceEquals(this.languageField, value) != true)) {
                    this.languageField = value;
                    this.RaisePropertyChanged("language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int numberInSeries {
            get {
                return this.numberInSeriesField;
            }
            set {
                if ((this.numberInSeriesField.Equals(value) != true)) {
                    this.numberInSeriesField = value;
                    this.RaisePropertyChanged("numberInSeries");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string seriesTitle {
            get {
                return this.seriesTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.seriesTitleField, value) != true)) {
                    this.seriesTitleField = value;
                    this.RaisePropertyChanged("seriesTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                if ((object.ReferenceEquals(this.titleField, value) != true)) {
                    this.titleField = value;
                    this.RaisePropertyChanged("title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Authors", Namespace="http://schemas.datacontract.org/2004/07/BookEntity")]
    [System.SerializableAttribute()]
    public partial class Authors : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<testWCFService.INetLibService.Author> authorsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<testWCFService.INetLibService.Author> authors {
            get {
                return this.authorsField;
            }
            set {
                if ((object.ReferenceEquals(this.authorsField, value) != true)) {
                    this.authorsField = value;
                    this.RaisePropertyChanged("authors");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Genres", Namespace="http://schemas.datacontract.org/2004/07/BookEntity")]
    [System.SerializableAttribute()]
    public partial class Genres : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<int> genresIDsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<int> genresIDs {
            get {
                return this.genresIDsField;
            }
            set {
                if ((object.ReferenceEquals(this.genresIDsField, value) != true)) {
                    this.genresIDsField = value;
                    this.RaisePropertyChanged("genresIDs");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Author", Namespace="http://schemas.datacontract.org/2004/07/BookEntity")]
    [System.SerializableAttribute()]
    public partial class Author : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string middleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string surnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fullName {
            get {
                return this.fullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.fullNameField, value) != true)) {
                    this.fullNameField = value;
                    this.RaisePropertyChanged("fullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string middleName {
            get {
                return this.middleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.middleNameField, value) != true)) {
                    this.middleNameField = value;
                    this.RaisePropertyChanged("middleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string surname {
            get {
                return this.surnameField;
            }
            set {
                if ((object.ReferenceEquals(this.surnameField, value) != true)) {
                    this.surnameField = value;
                    this.RaisePropertyChanged("surname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="INetLibService.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/selectBooksByAuthor", ReplyAction="http://tempuri.org/IService/selectBooksByAuthorResponse")]
		System.Collections.Generic.List<testWCFService.INetLibService.BookEntity> selectBooksByAuthor(string authorNameToSearch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/selectBooksByAuthor", ReplyAction="http://tempuri.org/IService/selectBooksByAuthorResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<testWCFService.INetLibService.BookEntity>> selectBooksByAuthorAsync(string authorNameToSearch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/selectBooksByTitle", ReplyAction="http://tempuri.org/IService/selectBooksByTitleResponse")]
        System.Collections.Generic.List<testWCFService.INetLibService.BookEntity> selectBooksByTitle(string titleToSearch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/selectBooksByTitle", ReplyAction="http://tempuri.org/IService/selectBooksByTitleResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<testWCFService.INetLibService.BookEntity>> selectBooksByTitleAsync(string titleToSearch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/selectBooksByGenre", ReplyAction="http://tempuri.org/IService/selectBooksByGenreResponse")]
        System.Collections.Generic.List<testWCFService.INetLibService.BookEntity> selectBooksByGenre(int genreIDToSearch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/selectBooksByGenre", ReplyAction="http://tempuri.org/IService/selectBooksByGenreResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<testWCFService.INetLibService.BookEntity>> selectBooksByGenreAsync(int genreIDToSearch);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/selectBookByID", ReplyAction="http://tempuri.org/IService/selectBookByIDResponse")]
        testWCFService.INetLibService.BookEntity selectBookByID(int bookID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/selectBookByID", ReplyAction="http://tempuri.org/IService/selectBookByIDResponse")]
        System.Threading.Tasks.Task<testWCFService.INetLibService.BookEntity> selectBookByIDAsync(int bookID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/extractBook", ReplyAction="http://tempuri.org/IService/extractBookResponse")]
        System.IO.Stream extractBook(testWCFService.INetLibService.BookEntity book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/extractBook", ReplyAction="http://tempuri.org/IService/extractBookResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> extractBookAsync(testWCFService.INetLibService.BookEntity book);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : testWCFService.INetLibService.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<testWCFService.INetLibService.IService>, testWCFService.INetLibService.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }

		public System.Collections.Generic.List<testWCFService.INetLibService.BookEntity> selectBooksByAuthor(string authorNameToSearch)
		{
            return base.Channel.selectBooksByAuthor(authorNameToSearch);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<testWCFService.INetLibService.BookEntity>> selectBooksByAuthorAsync(string authorNameToSearch) {
            return base.Channel.selectBooksByAuthorAsync(authorNameToSearch);
        }
        
        public System.Collections.Generic.List<testWCFService.INetLibService.BookEntity> selectBooksByTitle(string titleToSearch) {
            return base.Channel.selectBooksByTitle(titleToSearch);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<testWCFService.INetLibService.BookEntity>> selectBooksByTitleAsync(string titleToSearch) {
            return base.Channel.selectBooksByTitleAsync(titleToSearch);
        }
        
        public System.Collections.Generic.List<testWCFService.INetLibService.BookEntity> selectBooksByGenre(int genreIDToSearch) {
            return base.Channel.selectBooksByGenre(genreIDToSearch);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<testWCFService.INetLibService.BookEntity>> selectBooksByGenreAsync(int genreIDToSearch) {
            return base.Channel.selectBooksByGenreAsync(genreIDToSearch);
        }
        
        public testWCFService.INetLibService.BookEntity selectBookByID(int bookID) {
            return base.Channel.selectBookByID(bookID);
        }
        
        public System.Threading.Tasks.Task<testWCFService.INetLibService.BookEntity> selectBookByIDAsync(int bookID) {
            return base.Channel.selectBookByIDAsync(bookID);
        }
        
        public System.IO.Stream extractBook(testWCFService.INetLibService.BookEntity book) {
            return base.Channel.extractBook(book);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> extractBookAsync(testWCFService.INetLibService.BookEntity book) {
            return base.Channel.extractBookAsync(book);
        }
    }
}
